In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
x.grad  # this is where the gradients of y wrt x is stored, defaults to None

In [5]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
# if its not a vector, then take the sum of that vector before taking the gradient
x.grad.zero_()
y = x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [20]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u * x
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [27]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad = True)
print(a)
d = f(a)
print(d)
d.backward()

a.grad == d/a  # because anything in the function prduces a linear relationship between d and a

tensor(0.5240, requires_grad=True)
tensor(1073.1796, grad_fn=<MulBackward0>)


tensor(True)