In [57]:
import torch

In [58]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
x.shape

torch.Size([12])

In [60]:
x.numel()

12

In [61]:
X = x.reshape(3,4)

In [62]:
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [63]:
X[0:2,:] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [64]:
Z = torch.zeros_like(X)
Z
print(f'id(Z): {id(Z)}')

id(Z): 2025372417264


In [66]:
Z[:] = X + X  # gives the same address else address will change
print(f'id(Z): {id(Z)}')

id(Z): 2025372417264


In [67]:
Z += X
print(f'id(Z): {id(Z)}')

id(Z): 2025372417264
