**create a self-defined layer without parameters**

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.9372e-09, grad_fn=<MeanBackward0>)

**layers with parameters**

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.8462,  0.7929,  0.1926],
        [-0.2765,  0.6949, -0.0764],
        [-1.7230, -0.4755, -0.5864],
        [ 0.3320,  2.6161,  1.4829],
        [-0.9548, -0.3083,  0.9102]], requires_grad=True)

In [4]:
dense(torch.rand(2, 5))

tensor([[0.0000, 1.1781, 0.8963],
        [0.0000, 0.3187, 0.9950]])

**Using custom defined layers to build models**

In [6]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])