In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x15e5819b390>)

In [3]:
torch.cuda.device_count()

1

**check where the tensor is**

In [4]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [6]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i+1:
        return torch.device(f"cuda:{i}")
    return torch.device(cpu)

**put on GPU**

In [7]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [9]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [20]:
Y = torch.normal(0, 1, (2, 3), device="cuda:0")
Y = Y.cuda(0)
Y

tensor([[-0.5630,  0.8792, -0.0701],
        [ 0.0538,  0.0491, -0.9515]], device='cuda:0')

In [21]:
Z + Y

tensor([[0.4370, 1.8792, 0.9299],
        [1.0538, 1.0491, 0.0485]], device='cuda:0')

### NN on GPU

In [23]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())
net(X)
# everything is processed and stored on gpu

tensor([[0.2764],
        [0.2764]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [24]:
net[0].weight.data.device

device(type='cuda', index=0)